name: Code Review Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  code_review:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm install
        
      - name: Run ESLint for code analysis
        run: |
          echo "Running ESLint for code analysis..."
          npm run lint
        
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: "javascript"
          
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
        with:
          echo "Performing CodeQL Analysis..."
