name: Custom Workflow

on:
  push:
    branches:
      - main

jobs:
  generate_release_notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Release Notes
        run: |
          echo "Generating release notes..."
          git log --pretty=format:"%s" > ./release_notes.txt

      - name: Make Commits
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Display Commit Logs"
          git push origin main
     
