name: Documentation Generation

on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs: 
  generate-docs:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install JSDoc and jsdoc-to-markdown
        run: npm install --save-dev jsdoc-to-markdown@8.0.1

      - name: Generate documentation
        run: |
          npx jsdoc-to-markdown ./src/satellite.js > ./src/documentation.md 

      - name: Check for changes or create Markdown file
        run: |
          git diff --exit-code || touch ./src/documentation.md

      - name: Commit and push changes
        if: steps.commit_changes.outputs.changed == 'true'
        id: commit_changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update documentation"
          git push origin main

