name: Documentation Generation

on:
  push:
    branches:
      - main  

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install JSDoc and jsdoc-to-markdown
        run: npm install --save-dev jsdoc-to-markdown@8.0.1

      - name: Generate documentation
        run: |
          npx jsdoc-to-markdown ./src/utils.js > ./docs.md

      - name: Pull changes from main branch
        run: git pull origin main

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update documentation"
          git push origin main

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages