name: Scheduled Tasks

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main

jobs:
  maintenance:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run maintenance script
        run: |
          echo "Running maintenance tasks..."
          sudo apt-get update
          sudo apt-get upgrade -y
          # find "C:\Users\haniy\Desktop\semester6\scd\21i-1169-ass3\heavens-above-21i1169" -type f -name "*.log" -delete



